=== Chamsterr/Labs/Course 2/Term 2/Internet programming technology/03/ItCompany/files/plan.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="plan">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="first" type="employee"/>
        <xs:element name="second" type="employee"/>
        <xs:element name="third" type="employee"/>
        <xs:element name="forth" type="employee"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="employee">
    <xs:sequence>
      <xs:element name="name" type="nameType"/>

      <xs:element name="age" type="xs:int">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="16" />
            <xs:maxInclusive value="60" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="salary">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="100000" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="grade" type="GradesType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="GradesType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Junior"/>
      <xs:enumeration value="Middle"/>
      <xs:enumeration value="Senior"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="nameType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][a-z]+(\s[A-Z][a-z]+)*"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== Chamsterr/Labs/Course 2/Term 2/Internet programming technology/03/ItCompany/files/plan.xml
<?xml version="1.0" encoding="UTF-8"?>

<plan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plan.xsd">
  <first>
    <name>Maxim</name>
    <age>25</age>
    <salary>2500</salary>
    <grade>Junior</grade>
  </first>
  <second>
    <name>Mikita</name>
    <age>19</age>
    <salary>741</salary>
    <grade>Junior</grade>
  </second>
  <third>
    <name>Lee</name>
    <age>27</age>
    <salary>7089</salary>
    <grade>Senior</grade>
  </third>
  <forth>
    <name>Roman</name>
    <age>47</age>
    <salary>18112</salary>
    <grade>Senior</grade>
  </forth>
</plan>
