<?xmlversion = "1.0" encoding="UTF8"?>
<?xml-stylesheet type="text/css" href="1.css"?>
<!DOCTYPE PERSON[
<!ELEMENT body (PERSON, INFO, FIRST_NAME, LAST_NAME, AGE, COUNTRY, LOCATION, NATIVE_CITY)>
<!ELEMENT PERSON (INFO, FIRST_NAME, LAST_NAME, AGE, COUNTRY, LOCATION, NATIVE_CITY)>
<!ELEMENT INFO (#PCDATA)>
<!ELEMENT FIRST_NAME (#PCDATA)>
<!ELEMENT LAST_NAME (#PCDATA)>
<!ELEMENT AGE (#PCDATA)>
<!ELEMENT COUNTRY (#PCDATA)>
<!ELEMENT LOCATION (#PCDATA)>
<!ELEMENT NATIVE_CITY (#PCDATA)>
<!ENTITY LOCATION "Minsk">
<!ENTITY FIRST_NAME  "Nikita">
<!ENTITY LAST_NAME  "Kovkel">
]>

<!--FileName: 1.xml-->

<body>
  <PERSON>
      <INFO>info</INFO>
      <FIRST_NAME>first name: &FIRST_NAME; </FIRST_NAME>
      <LAST_NAME>last name: &LAST_NAME; </LAST_NAME>
      <AGE>age: 17</AGE>
      <COUNTRY>country: Belarus</COUNTRY>
      <LOCATION>location: &LOCATION;</LOCATION>
      <NATIVE_CITY>native city: Lida</NATIVE_CITY>
    </PERSON>

    <PERSON>
      <INFO>info</INFO>
      <FIRST_NAME>Abraham</FIRST_NAME>
      <LAST_NAME>Korshun</LAST_NAME>
      <AGE>15</AGE>
      <COUNTRY>Belarus</COUNTRY>
      <LOCATION>Minsk</LOCATION>
      <NATIVE_CITY>Minsk</NATIVE_CITY>
    </PERSON>

    <PERSON>
      <INFO>info</INFO>
      <FIRST_NAME>Boris</FIRST_NAME>
      <LAST_NAME>Laptop</LAST_NAME>
      <AGE>27</AGE>
      <COUNTRY>Russia</COUNTRY>
      <LOCATION>Moscow</LOCATION>
      <NATIVE_CITY>Moscow</NATIVE_CITY>
    </PERSON>
</body>
